### ISSUE TITLE
how to call image-copper-call yielded component  in template?

### ISSUE THREAD

**Issue by rinoldsimon** [danielthall/ember-cropperjs#13] opened 2018-08-07 16:59 UTC
`{{cropper.call 'crop()'}}` throws error `Assertion Failed: image-cropper-call crop() must be a function on [object Object]`

**Comment by ynotdraw** [comment] 2018-08-07 18:13
Hi @rinoldsimon, are you trying to call an action whenever the crop box moves? if so, you can just leverage `on` like:

```hbs
{{#image-cropper
  source=yourSource
  options=(hash
    aspectRatio=1
    viewMode=2
  ) as |cropper|}}

  {{cropper.on 'crop' action=(action 'cropImage')}}

{{/image-cropper}}
```

and in your controller:
```js
actions: {
  cropImage() {
    console.log(...arguments);
  }
}
```

**Comment by rinoldsimon** [comment] 2018-08-07 18:25
i want to call cropper method setCropBoxData()

**Comment by ynotdraw** [comment] 2018-08-07 19:18
Hm... we may have a bug with `call`.  I don't have the time right now to dig in, but can get back with you later this evening.  What you may also be able to do is utilize:

```hbs
{{cropper.on 'crop' action=(action 'cropImage')}}
```

and then in your action call it directly on the cropper instance, as it's returned:

```js
actions: {
  cropImage(cropper) {
    cropper.setCropBoxData(/* opts */);
  }
}
```

**Comment by rinoldsimon** [comment] 2018-08-07 19:30
one more thing, when i upload a different image and update the `source=*thelatestuploadedimageurl*`. The options are not getting set. 

Do i need to `reload` or `refresh` the `image-cropper` something like that ?
If it is so how it can be achieved ?

**Comment by ynotdraw** [comment] 2018-08-07 19:35
Can you tell me which version you are currently using? `0.4.2` should handle the case where the source changes.

**Comment by rinoldsimon** [comment] 2018-08-07 19:39
0.4.1. will try installing 0.4.2 and check it out

**Comment by ynotdraw** [comment] 2018-08-07 19:40
Thanks - if you find that it still doesn't work, would you mind filing another issue?

**Comment by rinoldsimon** [comment] 2018-08-07 19:47
got an erro 
`notarget No matching version found for ember-cropperjs@0.4.2`

**Comment by ynotdraw** [comment] 2018-08-07 19:54
@rinoldsimon 💩 sorry, 0.4.1 is the latest.  Dang.  Yeah, can you file another issue for the cropper source?  If you have any reproduction app you can share, that'd be amazing as well.  I understand if you can't though. Since this is a pre-1.0.0 release, I only have so many sample projects to test with.

**Comment by ynotdraw** [comment] 2018-08-07 20:25
Yeah, that should call `setCropBoxData` on the cropper instance directly. Are you still getting the `Uncaught RangeError: Maximum call stack size exceeded.` error?

**Comment by rinoldsimon** [comment] 2018-08-07 20:32
No. Works fine

**Comment by rinoldsimon** [comment] 2018-08-07 20:42
Only this ussue persist  https://github.com/danielthall/ember-cropperjs/issues/14

**Comment by ynotdraw** [comment] 2018-08-08 01:14
Okay awesome.  If alright with you then, I'll close this issue and take a look at #14.  I'll update the docs with this example as well to help other folks

**Comment by rinoldsimon** [comment] 2018-08-08 04:08
this doesn't solve the issue. When i move the `cropbox` to the different position because of the function 
```
_update(cropper) {
 cropper.setCropBoxData({"left":0,"top":0,"width":320,"height":320});
}
```
it again set to the position `left":0,"top":0,"width":320,"height":320`, when the `cropbox` is `moved`

My problem statement is, if there `previous cropboxdata` it will be stored in my server (which user sets the cropbox last time when they crop the image). Then next time when user opens the image the` cropbox` should set to the `previous cropboxdata` automatically when initialized. 

if i do that in `_update` method the function is keep calling all the time when the `cropbox` is moved

**Comment by ynotdraw** [comment] 2018-08-08 13:03
Oh I see, so basically you need a way to initialize the cropbox data with what's returned from your server on init (so page loads up, you request the cropbox data from your server, you feed that data into the cropper addon so it can set things up properly for the user)?

If that's the case, I think you will be able to use the `ready` event instead.  Can you give this a shot?  In your template:

```hbs
{{cropper.on 'ready' action=(action 'onCropperReady')}}
```

And then in your controller/component actions hash:

```js
actions: {
  onCropperReady(cropper) {
    cropper.setCropBoxData({"left":0,"top":0,"width":320,"height":320});
  }
}
```

**Comment by rinoldsimon** [comment] 2018-08-08 13:59
yeah got it worked !

**Closed** 2018-08-08 14:02 UTC
